#!/bin/bash

# place it in $HOME, since it is set in hypr.conf, make sure it is executable (chmod +x ./launch_bar)

if [[ ! $(pidof eww) ]]; then
	/home/xshiba/src/clones/eww/target/release/eww daemon
	sleep 1
fi

monitors=($(hyprctl monitors -j | jq -r '.[] | .id'))
for i in "${!monitors[@]}"; do
	/home/xshiba/src/clones/eww/target/release/eww open-many bar$i
	# /home/xshiba/src/clones/eww/target/release/eww open-many bar1
done
